### ISSUE TITLE
Map is extremely dark and hardly readable

### ISSUE THREAD

**Issue by Natanji** [LINKIWI/orion-web#34]
Can you offer an option to use a different kind of design, like the standard colorized OpenStreetMap view or its satellite version even? Or at least something with a bit more contrast in the map?

Right now, the focus clearly is on making the tracks and dots very visible, but it's very hard for me to make out where these points actually are on the real-world map. There is almost no difference in color/contrast between streets and the surrounding areas, or land and oceans. The street names are incredibly hard to read, too with their grey-on-grey coloring. The only thing I can actually read are the names of buildings/POIs.

**Comment by LINKIWI** [comment]
Sure, you can customize the map style by modifying https://github.com/LINKIWI/orion-web/blob/master/src/resources/data/map-style.json to your liking
