### ISSUE TITLE
Unable to run build on Ubuntu 18.04

### ISSUE THREAD

**Issue by Bungeetaco** [LINKIWI/orion-web#37]
Hi there!

I've been trying to run orion-web for about a day without succeeding. The build seems to fail while looking for a Babel plugin (transform-decorators-legacy) under .babelrc in root dir during the webpack build. I have not modified any files by myself. Any assistance would be appreciated, as I would love to get the application running to visualize the data gathered from the server instance.

Here is the information I've gathered from the attempted install:

OS: `Linux location 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 18.04.2 LTS (Bionic Beaver) `

Node.js: `v8.10.0`

Installed node_modules under orion-web: `acorn                                     color-string          fast-deep-equal                    is-binary-path             neo-async                         react-favicon              strip-ansi
acorn-dynamic-import                      combined-stream       fast-json-stable-stringify         is-buffer                  nice-try                          react-helmet               strip-eof
ajv                                       commander             fast-levenshtein                   is-callable                no-case                           react-icons                supercluster
ajv-errors                                commondir             fastparse                          is-data-descriptor         node-libs-browser                 react-is                   supports-color
ajv-keywords                              component-emitter     figgy-pudding                      is-date-object             normalize-path                    react-lifecycles-compat    symbol-observable
ansicolors                                concat-map            filename-regex                     is-descriptor              npm-run-path                      react-map-gl               tapable
ansi-regex                                concat-stream         file-type                          is-dotfile                 nth-check                         react-redux                terminal-char-width
ansi-styles                               connect               fill-range                         is-equal-shallow           number-is-nan                     react-router               terser
anymatch                                  console-browserify    finalhandler                       isexe                      oauth-sign                        react-router-dom           terser-webpack-plugin
app                                       constants-browserify  find-cache-dir                     is-extendable              object-assign                     react-side-effect          through
app-client                                convert-source-map    find-up                            is-extglob                 object-copy                       readable-stream            through2
aproba                                    copy-concurrently     findup-sync                        is-finite                  object.getownpropertydescriptors  read-chunk                 timers-browserify
array-unique                              copy-descriptor       flat-colors                        is-fullwidth-code-point    object-inspect                    readdirp                   tinycolor2
arr-diff                                  core-js               flush-write-stream                 is-function                object-keys                       recast                     tiny-invariant
arr-flatten                               core-util-is          foreach                            is-glob                    object.omit                       redeyed                    tinyqueue
arr-union                                 cornerstone           for-each                           is-number                  object.pick                       redux                      tiny-warning
asciify-image                             couleurs              forever-agent                      isobject                   object-visit                      regenerator-runtime        to-arraybuffer
asn1                                      create-ecdh           for-in                             is-plain-object            once                              regex-cache                to-fast-properties
asn1.js                                   create-hash           form-data                          is-posix-bracket           on-finished                       regex-not                  to-object-path
assert                                    create-hmac           for-own                            is-primitive               optimist                          regexp-clone               toposort
assert-plus                               cross-spawn           fragment-cache                     is-regex                   optionator                        relateurl                  to-regex
assign-symbols                            crypto-browserify     from2                              isstream                   os-browserify                     remove-trailing-separator  to-regex-range
ast-types                                 csscolorparser        fs-readdir-recursive               is-stream                  os-homedir                        renderkid                  tough-cookie
async                                     css-select            fs.realpath                        is-symbol                  os-locale                         repeat-element             trim-right
async-each                                css-what              fs-write-stream-atomic             is-typedarray              os-tmpdir                         repeating                  tslib
asynckit                                  cyclist               functional-match                   is-windows                 output-file-sync                  repeat-string              tty-browserify
atob                                      d3-ease               function-bind                      jimp                       pako                              request                    tunnel-agent
aws4                                      d3-hexbin             geojson-rewind                     jpeg-js                    parallel-transform                require-directory          tweetnacl
aws-sign2                                 dashdash              geojson-vt                         jsbn                       param-case                        require-main-filename      type-check
@babel                                    date-now              geolib                             jsesc                      parse-asn1                        require_optional           typedarray
babel-cli                                 debug                 get-caller-file                    json5                      parse-bmfont-ascii                resolve                    typpy
babel-code-frame                          decamelize            getpass                            json-parse-better-errors   parse-bmfont-binary               resolve-cwd                uglify-js
babel-core                                @deck.gl              get-stream                         json-schema                parse-bmfont-xml                  resolve-dir                uglifyjs-webpack-plugin
babel-generator                           deck.gl               get-value                          json-schema-traverse       parse-glob                        resolve-from               unfetch
babel-helpers                             decode-uri-component  gl-mat3                            json-stringify-safe        parse-headers                     resolve-pathname           union-value
babel-loader                              deep-equal            gl-mat4                            jsprim                     parse-passwd                      resolve-protobuf-schema    unique-filename
babel-messages                            deep-is               gl-matrix                          js-tokens                  parseurl                          resolve-url                unique-slug
babel-plugin-syntax-decorators            define-properties     glob                               kareem                     pascalcase                        ret                        unpipe
babel-plugin-transform-decorators-legacy  define-property       global                             kdbush                     path-browserify                   rimraf                     unset-value
babel-polyfill                            delayed-stream        global-modules                     kind-of                    path-dirname                      ripemd160                  upath
babel-register                            des.js                global-prefix                      lcid                       path-exists                       run-queue                  upper-case
babel-runtime                             detect-file           globals                            levn                       path-is-absolute                  rw                         uri-js
babel-template                            detect-indent         glob-base                          load-bmfont                path-key                          safe-buffer                urix
babel-traverse                            diffie-hellman        glob-parent                        loader-runner              path-parse                        safer-buffer               url
babel-types                               domain-browser        gl-quat                            loader-utils               path-to-regexp                    safe-regex                 url-join
babylon                                   dom-converter         gl-vec2                            locate-path                pbf                               saslprep                   url-regex
balanced-match                            domelementtype        gl-vec3                            lodash                     pbkdf2                            sax                        use
base                                      domhandler            gl-vec4                            loose-envify               p-defer                           scheduler                  user-home
base64-js                                 dom-serializer        graceful-fs                        lower-case                 performance-now                   schema-utils               util
bcrypt-pbkdf                              domutils              grid-index                         lru-cache                  p-finally                         seer                       utila
big.js                                    dom-walk              hammerjs                           luma.gl                    phin                              semver                     util-deprecate
bignumber.js                              dotenv                har-schema                         magic-string               pify                              serialize-javascript       util.promisify
binary-extensions                         dottie                har-validator                      make-dir                   p-is-promise                      set-blocking               utils-merge
bluebird                                  duplexer2             has                                mamacro                    piwik-react-router                setimmediate               uuid
bmp-js                                    duplexify             has-ansi                           map-age-cleaner            pixelmatch                        set-value                  v8-compile-cache
bn.js                                     earcut                has-flag                           @mapbox                    pkg-dir                           sha.js                     v8flags
boolbase                                  ecc-jsbn              hash-base                          mapbox-gl                  p-limit                           shallow-copy               value-equal
brace-expansion                           ee-first              hash.js                            map-cache                  p-locate                          shallowequal               verror
braces                                    elliptic              has-symbols                        map-visit                  pngjs                             sharkdown                  viewport-mercator-project
brfs                                      emojis-list           has-value                          math.gl                    posix-character-classes           shebang-command            vlq
brorand                                   encodeurl             has-values                         math-random                potpack                           shebang-regex              vm-browserify
browserify-aes                            end-of-stream         he                                 md5.js                     prelude-ls                        signal-exit                vt-pbf
browserify-cipher                         enhanced-resolve      history                            mem                        preserve                          simple-swizzle             warning
browserify-des                            entities              hmac-drbg                          memory-fs                  pretty-error                      slash                      watchpack
browserify-rsa                            env                   hoist-non-react-statics            memory-pager               private                           sliced                     @webassemblyjs
browserify-sign                           errno                 homedir-polyfill                   merge-source-map           probe.gl                          snapdragon                 webgl-debug
browserify-zlib                           es6-promise           home-or-tmp                        micromatch                 process                           snapdragon-node            webpack
bson                                      es6-templates         html-loader                        miller-rabin               process-nextick-args              snapdragon-util            webpack-cli
buffer                                    es-abstract           html-minifier                      mime                       promise-inflight                  source-list-map            webpack-sources
buffer-equal                              escape-html           htmlparser2                        mime-db                    prop-types                        source-map                 wgs84
buffer-from                               escape-string-regexp  html-webpack-inline-source-plugin  mime-types                 protocol-buffers-schema           source-map-resolve         which
buffer-xor                                escodegen             html-webpack-plugin                mimic-fn                   prr                               source-map-support         which-module
builtin-status-codes                      eslint-scope          https-browserify                   min-document               pseudomap                         source-map-url             window-size
cacache                                   esprima               http-signature                     minimalistic-assert        psl                               sparse-bitfield            wordwrap
cache-base                                esrecurse             humanize                           minimalistic-crypto-utils  p-try                             split                      worker-farm
camelcase                                 es-to-primitive       humanize-duration                  minimatch                  public-encrypt                    split-string               wrap-ansi
camel-case                                estraverse            ieee754                            minimist                   pump                              sshpk                      wrappy
cardinal                                  esutils               iferr                              mississippi                pumpify                           ssri                       x256
caseless                                  events                immutable                          mixin-deep                 punycode                          static-eval                xhr
chalk                                     evp_bytestokey        import-local                       mjolnir.js                 qs                                static-extend              xml2js
chokidar                                  execa                 imurmurhash                        mkdirp                     querystring                       static-module              xmlbuilder
chownr                                    exenv                 indexof                            modulator                  querystring-es3                   statuses                   xml-parse-from-string
chrome-trace-event                        exif-parser           inflight                           mongodb                    quickselect                       stream-browserify          xtend
cipher-base                               expand-brackets       inherits                           mongodb-core               quote-stream                      stream-each                @xtuc
class-utils                               expand-range          ini                                mongoose                   randomatic                        stream-http                y18n
clean-css                                 expand-tilde          interpret                          mongoose-legacy-pluralize  randombytes                       stream-shift               yallist
cliui                                     expect.js             invariant                          move-concurrently          randomfill                        stream-spigot              yargs
code-point-at                             extend                invert-kv                          mpath                      raven-js                          stream-to                  yargs-parser
collection-visit                          extend-shallow        ip-regex                           mquery                     react                             stream-to-buffer
color                                     extglob               is-accessor-descriptor             ms                         react-dom                         string_decoder
color-convert                             extsprintf            isarray                            murmurhash-js              react-elemental                   string.prototype.trim
color-name                                falafel               is-arrayish                        nanomatch                  react-elemental-fonts             string-width
`

Attempting to run `npm run build` outputs the following:

> bungee@location:~/orion-web$ NODE_ENV=production MAPBOX_API_TOKEN=pk.xxxxxxxxxxxxxxxxxxxxxxxxxxxxx ORION_SERVER_URL=http://orion.example.com npm run build
> 
> orion-web@0.0.1 build /home/bungee/orion-web
> webpack
> 
> Hash: 2f01f64896cdb23944ac
> Version: webpack 4.29.6
> Time: 1379ms
> Built at: 03/23/2019 4:00:06 PM
> 1 asset
> Entrypoint main = main.js
> [0] ./src/index.js 1.4 KiB {0} [built] [failed] [1 error]
> 
> ERROR in ./src/index.js
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> **TypeError: Plugin 0 specified in "/home/bungee/orion-web/.babelrc" was expected to return a function but returned "undefined"**
>     at Function.normalisePlugin (/home/bungee/orion-web/node_modules/babel-core/lib /transformation/file/options/option-manager.js:148:15)
>     at /home/bungee/orion-web/node_modules/babel-core/lib/transformation/file/options /option-manager.js:184:30
>     at Array.map (<anonymous>)
>     at Function.normalisePlugins (/home/bungee/orion-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/bungee/orion-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/bungee/orion-web/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/bungee/orion-web/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/bungee/orion-web/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/bungee/orion-web/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/bungee/orion-web/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/home/bungee/orion-web/node_modules/babel-loader/lib/index.js:173:20)
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/resources/templates/index.html 232 bytes {0} [built]
> 
> npm ERR! Linux 4.15.0-46-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> npm ERR! orion-web@0.0.1 build: `webpack`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the orion-web@0.0.1 build script 'webpack'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the orion-web package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     webpack
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs orion-web
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls orion-web
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/bungee/orion-web/npm-debug.log

Here is the output of npm-debug.log:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle orion-web@0.0.1~prebuild: orion-web@0.0.1
6 silly lifecycle orion-web@0.0.1~prebuild: no script for prebuild, continuing
7 info lifecycle orion-web@0.0.1~build: orion-web@0.0.1
8 verbose lifecycle orion-web@0.0.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle orion-web@0.0.1~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/bungee/orion-web/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle orion-web@0.0.1~build: CWD: /home/bungee/orion-web
11 silly lifecycle orion-web@0.0.1~build: Args: [ '-c', 'webpack' ]
12 silly lifecycle orion-web@0.0.1~build: Returned: code: 2  signal: null
13 info lifecycle orion-web@0.0.1~build: Failed to exec build script
14 verbose stack Error: orion-web@0.0.1 build: `webpack`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid orion-web@0.0.1
16 verbose cwd /home/bungee/orion-web
17 error Linux 4.15.0-46-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error orion-web@0.0.1 build: `webpack`
22 error Exit status 2
23 error Failed at the orion-web@0.0.1 build script 'webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the orion-web package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs orion-web
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls orion-web
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Hopefully this is enough information. Please do let me know if you need me to provide further details. :smiley:

**Comment by LINKIWI** [comment]
Hm, I'm not able to reproduce even after replicating your environment of 18.04 and Node 8.10.0. What commit SHA are you on? Are you sure you are pulling in the correct versions of all the build dependencies? Can you paste the output of `npm ls --depth 0`?

Can you try reproducing in a clean environment (e.g. spin up a Docker container and try building from within there)?

**Comment by Bungeetaco** [comment]
Sure thing! Here's the output of `npm ls --depth 0`:

> bungee@location:~/orion-web$ npm ls --depth 0
> orion-web@0.0.1 /home/bungee/orion-web
> ├── app@0.1.0 extraneous
> ├── babel-cli@6.26.0 extraneous
> ├── babel-core@6.26.3
> ├── babel-loader@7.1.5
> ├── babel-plugin-transform-decorators-legacy@1.3.5
> ├── color@3.1.0
> ├── d3-ease@1.0.5
> ├── deck.gl@5.3.5
> ├── deep-equal@1.0.1
> ├── dotenv@6.2.0
> ├── dottie@2.0.1
> ├── env@0.0.2 extraneous
> ├── functional-match@0.0.2
> ├── geolib@2.0.24
> ├── history@4.9.0
> ├── html-loader@0.5.5
> ├── html-webpack-inline-source-plugin@0.0.10
> ├── html-webpack-plugin@3.2.0
> ├── humanize@0.0.9
> ├── humanize-duration@3.18.0
> ├── mapbox-gl@0.48.0
> ├── piwik-react-router@0.12.1
> ├── prop-types@15.7.2
> ├── raven-js@3.27.0
> ├── react@16.8.5
> ├── react-dom@16.8.5
> ├── react-elemental@1.2.0
> ├── react-elemental-fonts@0.0.2
> ├── react-favicon@0.0.14
> ├── react-helmet@5.2.0
> ├── react-icons@3.5.0
> ├── react-map-gl@3.3.9
> ├── react-redux@5.1.1
> ├── react-router@4.3.1
> ├── react-router-dom@4.3.1
> ├── redux@4.0.1
> ├── uglifyjs-webpack-plugin@1.3.0
> ├── unfetch@3.1.2
> ├── viewport-mercator-project@5.3.0
> ├── webpack@4.29.6
> └── webpack-cli@3.3.0
> 
> npm ERR! extraneous: app@0.1.0 /home/bungee/orion-web/node_modules/app
> npm ERR! extraneous: babel-cli@6.26.0 /home/bungee/orion-web/node_modules/babel-cli
> npm ERR! extraneous: env@0.0.2 /home/bungee/orion-web/node_modules/env
> npm ERR! peer dep missing: acorn@^6.0.0, required by acorn-dynamic-import@4.0.0

I'll spin up a Debian stretch install, repeat the installation steps and report back.

**Comment by Bungeetaco** [comment]
As for the commit, I simply pulled `git clone https://github.com/LINKIWI/orion-web.git` as per the readme, so I'm not sure but I believe it would be the latest one: https://github.com/LINKIWI/orion-web/commit/3ef949dfc908d380025a4d32e1e80206c71ff004

**Comment by Bungeetaco** [comment]
Alright so,

I started from scratch using a fresh install of Debian Stretch and the official NodeJS 8.x repo. I was then able to complete the build successfully. I did get an error about webpack being missing from the module list, but that was quickly fixed by doing `npm install webpack` (maybe it could be added to the list of depencies being downloaded on initial install, if it's not already?). The only differences this time are the OS and the Node.js version.

The default Bionic apt npm package sat at v8.10 while the Official Node.js repo packages (https://github.com/nodesource/distributions/blob/master/README.md#debinstall) are currently at v8.15.1.

It seems the default npm package via apt might be outdated or is missing something in order for orion-web to build properly. I spun up another Ubuntu VM on top of the Debian one just to make sure, and was able to reproduce the issue I mentioned above using the apt npm package once again.

I then started from a snapshot on the Ubuntu instance back to vanilla, tried installing the Node.JS v8.x repo rather than the apt package, followed the installation process for orion-web again, and was successful on building for Ubuntu 18.04 that time.

Everything seems to be working properly now. I would perhaps add a mention to the readme to use the official Node.js libraries rather than the ones built into the package manager, if that turns out to be the issue. I'm not sure how they're all managed or if version changes within npm can cause these kind of issues. 

P.S For future reference, would you be willing to confirm your target installation sources/app versions when you built orion-web on your end?

Thanks again for the quick reply and for your assistance. Love the app you created! :smile:

**Comment by LINKIWI** [comment]
I see, yeah I'll add a note to the README about Node installation if it's not already there. Thanks for the heads up. I'll also double check the dependencies to make sure webpack is included.

I built the project on Ubuntu 16.04 using Node v10.15.3 (latest LTS at the time of this writing). All commits going into master should be able to build without errors in this environment since otherwise my CI would not have mirrored the commit to Github.
