### ISSUE TITLE
Not appreciative of sentry reporting in the JS

### ISSUE THREAD

**Issue by arahayrabedian** [LINKIWI/orion-web#39]
Hi,

Wanted to say that whilst i appreciate the work you've done to put this project together (and thank you for it) that I must highlight that the rolled-in sentry reporting/setup/phone-home is not appreciated. I had to manually yank sentry reporting to your domain out of the javascript code as it was triggering. Behaviour like that is generally not welcome in projects like this without clear information about it and an option to disable it.

It may of course have been a mistake or oversight, in which case I would like to see it get pulled out by default.

Thanks

**Comment by LINKIWI** [comment]
The project is open source and MIT licensed; you are free to modify it as you wish. The Sentry reporting is to help me identify bugs and errors that I haven't encountered in my own environment.
